INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Computers');
INSERT INTO tb_category (name) VALUES ('Mobile Phones');
INSERT INTO tb_category (name) VALUES ('Category 1');
INSERT INTO tb_category (name) VALUES ('Category 2');
INSERT INTO tb_category (name) VALUES ('Category 3');
INSERT INTO tb_category (name) VALUES ('Category 4');
INSERT INTO tb_category (name) VALUES ('Category 5');
INSERT INTO tb_category (name) VALUES ('Category 6');
INSERT INTO tb_category (name) VALUES ('Category 7');
INSERT INTO tb_category (name) VALUES ('Category 8');
INSERT INTO tb_category (name) VALUES ('Category 9');
INSERT INTO tb_category (name) VALUES ('Category 10');
INSERT INTO tb_category (name) VALUES ('Category 11');
INSERT INTO tb_category (name) VALUES ('Category 12');
INSERT INTO tb_category (name) VALUES ('Category 13');
INSERT INTO tb_category (name) VALUES ('Category 14');
INSERT INTO tb_category (name) VALUES ('Category 15');
INSERT INTO tb_category (name) VALUES ('Category 16');
INSERT INTO tb_category (name) VALUES ('Category 17');
INSERT INTO tb_category (name) VALUES ('Category 18');
INSERT INTO tb_category (name) VALUES ('Category 19');
INSERT INTO tb_category (name) VALUES ('Category 20');